name: Update Last Modified Date

on:
  push:
    branches:
      - main

jobs:
  update-last-modified-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Last Modified Date
        run: |
          for file in $(find . -type f -name '*.md'); do
            last_modified_time=$(git log -1 --format=%ai -- $file)
            last_modified_date=$(date -d "$last_modified_time" +"%Y-%m-%d %H:%M:%S %z")
            sed -i "1s/^/last_modified_date: $last_modified_date\n/" $file
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update last modified date"
          git push
